### ISSUE TITLE
Login with different button 

### ISSUE THREAD

**Issue by NBibikov** [alexfedosov/AFULoginSDK#2]
Hi! Thanks for library. Can you help me understand how to make login with button for facebook and twitter

```
- (IBAction)facebookLoginButton:(UIButton *)sender {

}

- (IBAction)twitterLoginButton:(UIButton *)sender {

}
```

**Comment by alexfedosov** [comment]
Hi, @NBibikov 

your have problem because of ULDefaultConfigurator was designed for login with multiple providers.
 So first, you should subclass from it and make possible to pass one provider:

``` obj-c

@interface ULOneProviderConfigurator : ULDefaultConfigurator
@property (nonatomic) id<ULProvider> provider;
@end

@implementation ULOneProviderConfigurator
- (NSArray *)providers{
    return @[self.provider];
}

@end
```

Then you can write something like:

``` obj-c
- (void)loginViaProvider:(id<ULProvider>)provider{
    ULOneProviderConfigurator *configurator = [ULOneProviderConfigurator new];
    configurator.provider = provider;
    [[uLogin sharedInstance] startLogin:configurator
                         viewController:self
                             completion:^(ULUserProfileData *userProfileData, id<ULProvider> authProvider, NSString *uLoginToken) {
                             }];

}
```

And use it for login via FB or Twitter

``` obj-c
- (IBAction)facebookLoginButton:(UIButton *)sender {
       [self loginViaProvider:[ULProviderFacebook new]];
}

- (IBAction)twitterLoginButton:(UIButton *)sender {
       [self loginViaProvider:[ULProviderTwitter new]];
}
```

**Comment by NBibikov** [comment]
Super! That works!
And one more question - there are any logo or фdvertising on login screen? This screen will not be showing for my app?
![screen shot 2015-09-02 at 4 23 27 pm](https://cloud.githubusercontent.com/assets/8437488/9632333/34ab4c8e-518f-11e5-8311-3268c838a802.png)

**Comment by alexfedosov** [comment]
Sorry, I do not know about this, because I'm not part of ULogin team. They can display any info in login view if they want. But promise that my code will not display any ads or logos

**Comment by NBibikov** [comment]
Have you used this library in your projects? This shows some additional info?

**Comment by alexfedosov** [comment]
If login provider does not return some of required fields (for example email) - uLogin will show screen to ask this info as in your screenshot above

**Comment by NBibikov** [comment]
ок, thank you for quick response!
